name: docs.yml
on:
  push:
    branches:
      - master

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.19.3 ]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: yarn install

      - name: Build
        run: yarn build:pages "lti-typescript"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build
        run: yarn build:pages "lti-typescript"


      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: compiled
          path: lti-typescript/
          retention-days: '1'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        env:
          REPO: self
          BRANCH: pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
