name: docs.yml
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.19.3 ]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: yarn install

      - name: Build
        run: yarn build:pages "lti-typescript"

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: pages
          FOLDER: lti-typescript
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}" # The commit message

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        env:
          REPO: self
          BRANCH: pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
